server:
  #443
  port: 443
  ssl:
    key-store: classpath:tomcat.keystore
    key-store-password: 123456
    key-alias: tomcat
    key-store-type: JKS

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.89.20:3306/meetingsystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: lw091211


mybatis:
  mapper-locations: classpath:mapper/*.xml


